[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --html=reports/report.html --self-contained-html


;Means
;testpaths       → look for tests inside tests/
;python_files    → collect files starting with test_
;python_functions→ collect functions starting with test_
;addopts = -v    → automatically run in verbose mode

;use verbose output
;generate reports/report.html
;create it as a self-contained HTML report